### ISSUE TITLE
staging feedback

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/bitcoinsearch-app#114]
based on https://bitcoinsearch-43t9q2gbz-btc-knowledge-base.vercel.app/

<img width="1023" alt="Screenshot 2024-05-01 at 4 45 32 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/a55c29f1-22ca-4d99-8ae8-6db89fa1b2d2">
This leaks too far down (below the fold, shorten it)

<img width="502" alt="Screenshot 2024-05-01 at 4 46 07 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/0c4de7fd-70c7-4380-878d-23d7dc7ae143">
Github item isn't visible

<img width="706" alt="Screenshot 2024-05-01 at 4 47 57 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/9e8b2fc5-dd2d-4c35-8849-9b61ff1c00da">
Some spans are links and some aren't. Why is the date a link but the icon or source isn't?
Remove the https:// from all urls. It makes them unnecessarily long.

<img width="384" alt="Screenshot 2024-05-01 at 4 50 07 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/ae128fb9-b0bd-43fb-954e-8fefc8a7ca71">
Are the app descriptions the same font as the rest of the site? Why is the dev project in grey and the others in black?

<img width="832" alt="Screenshot 2024-05-01 at 4 52 32 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/fec9ba96-75be-4ade-9ddb-fc1b6c192e52">
Sources leak onto a second row

Here they are all two rows and but don't fill up the width of the div
<img width="657" alt="Screenshot 2024-05-01 at 4 54 20 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/586061bc-be7d-47c9-88de-d547166711d1">

<img width="669" alt="Screenshot 2024-05-01 at 4 53 09 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/ef25a804-d94d-4d5e-995d-9df5c80281d2">
Gnusha should be bitcoin-dev mailing list

**Comment by adamjonas** [comment]
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/93f84f85-3dda-4756-8814-e021090dc822)
If I click on the search bar in mobile I get all the suggestions plus my keyboard pops up. This is hard for me to navigate. I have doubts whether the suggestions, as currently implemented, will work on mobile.

The Bitcoin dev mailing list who isn't be labeled as the Linuxfoundation 
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/6f7682bf-b692-4a86-8ad2-39eebafd37d2)

This url in the search bar is really ugly and has no semantic meaning
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/8531c3c0-8ed5-417c-a66d-d8c334c427dc)

Can't scroll down the app list on mobile
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/baec781d-732c-42dd-85e5-da330e3bd07a)

The filter button is disabled once I open the filter menu. I have to use a different button and it's not clear on mobile what that icon represents. 
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/ef25b3b3-6050-43e2-9505-6868c8dcc4f3)

Is this how we want to footer to look in dark mode mobile? At the very least the GitHub icon doesn't look consistent with the other items. 
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/c6ea4ace-d35a-4052-a562-554f371ea01e)

The font size on mobile feels small
![image](https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/7e4ece83-1cae-421a-a1f2-ecb6a5069742)

**Comment by Emmanuel-Develops** [comment]
> Some spans are links and some aren't. Why is the date a link but the icon or source isn't?
The card itself (the container) is clickable and takes the user to the link. By icon and source are you referring to the source domain (e.g https://bitcoinops.org/en/)?

**Comment by Emmanuel-Develops** [comment]
> Are the app descriptions the same font as the rest of the site?

There are 2 fonts used globally in the site, 
- Geist
- Mona Sans
The font used in the app descriptions is 'Mona Sans', which is the same font used in filters.
> Why is the dev project in grey and the others in black?
design guide, not sure there's a specific reason for that. Maybe showcase parent?, while the rest apps are under that parent.

**Comment by Emmanuel-Develops** [comment]
> Github item isn't visible

fixed in latest commit

**Comment by aassoiants** [comment]
Made into task list

Desktop
- [ ] This leaks too far down (below the fold, shorten it)
- [ ] Github item isn't visible
- [ ] Some spans are links and some aren't. Why is the date a link but the icon or source isn't? Remove the https:// from all urls. It makes them unnecessarily long.
- [ ] Are the app descriptions the same font as the rest of the site? Why is the dev project in grey and the others in black?
- [ ] Sources leak onto a second row
- [ ] Here they are all two rows and but don't fill up the width of the div
- [ ] Gnusha should be bitcoin-dev mailing list

Mobile
- [ ] If I click on the search bar in mobile I get all the suggestions plus my keyboard pops up. This is hard for me to navigate. I have doubts whether the suggestions, as currently implemented, will work on mobile.
- [ ] The Bitcoin dev mailing list who isn't be labeled as the Linuxfoundation
- [ ] This url in the search bar is really ugly and has no semantic meaning
- [ ] Can't scroll down the app list on mobile
- [ ] The filter button is disabled once I open the filter menu. I have to use a different button and it's not clear on mobile what that icon represents.
- [ ] Is this how we want to footer to look in dark mode mobile? At the very least the GitHub icon doesn't look consistent with the other items.
- [ ] The font size on mobile feels small

**Comment by Emmanuel-Develops** [comment]
> Gnusha should be bitcoin-dev mailing list

We'll need to discuss how we scrape it then or merge them.
For now `bitcoin-dev via Gnusha` can work.
Because they are seen as separate entities in the index and a duplicate `bitcoin-dev` domain filter may be confusing

**Comment by aassoiants** [comment]
@Emmanuel-Develops i like the `bitcoin-dev (gnusha)` solution

**Comment by adamjonas** [comment]
These pills are still not aligned:
<img width="817" alt="Screenshot 2024-05-08 at 3 41 28 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/dc90203e-ec77-4ffa-89c2-65c8a8beb0f1">

---

The author pill isn't consistent when there isn't a date attached to a record
<img width="666" alt="Screenshot 2024-05-08 at 3 41 57 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/0dcdf71a-b537-4220-a0ab-494d2c7b1c0c">

---

The formatting here isn't going to work. Also just call it all the bitcoin-dev mailing list. There is no reason to differentiate.

<img width="687" alt="Screenshot 2024-05-08 at 3 43 02 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/3a85113c-9916-47fd-b91f-fcb9ce13b973">

---

This passed validation:
<img width="546" alt="Screenshot 2024-05-08 at 3 44 04 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/0592ad40-312c-40c6-98ff-0a64fb7659e6">

---

Two things here. 1) there is a white boarder on the rounded corners that doesn't look right. 2) That big green button looks like a button. But it's not a button. It should be a button that closes the modal.
<img width="642" alt="Screenshot 2024-05-08 at 3 44 33 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/14f79937-7472-4cd8-a716-85d81e45c5a6">

**Comment by Emmanuel-Develops** [comment]
cc: @adamjonas 
> These pills are still not aligned:

I need clarity on this? is it the wrap to another row?

> The author pill isn't consistent when there isn't a date attached to a record

good observation, I'll fix that.

> The formatting here isn't going to work. Also just call it all the bitcoin-dev mailing list. There is no reason to differentiate.

we use the same naming for filtering domains. There's a json where we mapped the URLs and their respective display names.
<img width="323" alt="Screenshot 2024-05-09 at 2 37 43 AM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/62019510/144c8d35-f329-4f28-809c-f22f27e07c1e">
<img width="299" alt="Screenshot 2024-05-09 at 2 39 17 AM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/62019510/1f1ba031-1b5f-4b7d-b5ac-45b6870e1839">

using `Bitcoin Dev mailing list` will be confusing as shown in the second image above. A hacky solution could be conditionally look for "gnusha" URLs in the results and display as `Bitcoin Dev mailing list` while leaving filter as `Bitcoin Dev (Gnusha)` (not a fan!)

**Comment by Emmanuel-Develops** [comment]
>This passed validation:

fixed (switched from native HTML URL and email validation to regex)

> after I submit a source the url input clears and there is a notable delay before the submitted successfully modal comes up. I didn't it twice and each time it felt like I did something wrong.

fixed (added loading visual cue, prevented double submit)

> Two things here. 1) there is a white boarder on the rounded corners that doesn't look right. 2) That big green button looks like a button. But it's not a button. It should be a button that closes the modal.

fixed

> Is this the number of filters I have? The alignment makes it looks like a mistake. Also, this is only visible in light mode and totally invisible in dark mode.

fixed

**Comment by adamjonas** [comment]
>  is it the wrap to another row?
Yes. Why do we need so many that some leak onto the next row?

Re 
<img width="323" alt="329098955-144c8d35-f329-4f28-809c-f22f27e07c1e" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/755825/cbd3a736-45ae-4c7d-b444-ba1e60232401">
How are you expecting a seacher to know the difference. Combine them and have the filters search both.

**Comment by Emmanuel-Develops** [comment]
> Yes. Why do we need so many that some leak onto the next row?

I guess less leakage is good for mobile (I don't have much of a preference on this). I've set it to only one row so wider screens show more pills.
<img width="360" alt="Screenshot 2024-05-09 at 7 56 28 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/62019510/da3ae953-767e-4ef0-83a5-586901f93d23"><img width="360" alt="Screenshot 2024-05-09 at 7 53 08 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/62019510/b0247101-03d3-4763-9064-451e8777781b"><img width="460" alt="Screenshot 2024-05-09 at 7 53 33 PM" src="https://github.com/bitcoinsearch/bitcoinsearch-app/assets/62019510/fdcc0c64-3014-4518-b06e-1567e55e315e">

**Comment by Emmanuel-Develops** [comment]
> How are you expecting a seacher to know the difference? Combine them and have the filters search both.

Combining on the FE will be a very hacky approach (based on how the logic is setup). Its better to combine in the index itself.
Is this critical for launch?

**Comment by adamjonas** [comment]
They can't be combined on elastic search. They come from different sources.
